config/routes.rb
CssForDevelopers::Application.routes.draw do
  root :to => 'home#index'

  resources :pages

  get "home/(:action)" => "home"
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :parent_id, :content, :name

  has_ancestry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/css_controller.rb
class CssController < ApplicationController
  def index
  end

  def css
  end

  def less
  end

  def sass
  end

  def twitter_bootstrap
  end

  def zurb
  end

  def blueprint
  end
end

app/controllers/dotnet_controller.rb
class DotnetController < ApplicationController
  def index
  end

  def mvc
  end

  def silverlight
  end

  def utilities
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def fixed_grid

  end

  def fluid_grid

  end

  def responsive_visibility

  end

end

app/controllers/javascript_controller.rb
class JavascriptController < ApplicationController
  def index
  end

  def jquery
  end

  def jquery_ui
  end

  def node
  end

  def backbone
  end
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base
  respond_to :html, :xml, :json
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_iframe url
    "<iframe src=\"#{url}\" frameborder=\"0\" height=\"1000px\" width=\"100%\"></iframe>".html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<h1>CSS for developers</h1>

<h2>Css compiler: Less</h2>
<h3></h3>
<ul>
  <li><%= link_to "Example", "/less_exercises" %></li>
</ul>

<h2>Css framework: Twitter Bootstrap</h2>
<h3>Grid system</h3>
<ul>
  <li><%= link_to "Fixed Grid", "/home/fixed_grid" %></li>
  <li><%= link_to "Fluid Grid", "/home/fluid_grid" %></li>
  <li><%= link_to "Visibility", "/home/responsive_visibility" %></li>
</ul>

<h3>Cms</h3>
<ul id="menu">
  <% for page in Page.roots %>
      <li><%= link_to page.name, page %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "CMS" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<br>
<br>
<br>
<div><%= link_to "Home", root_path %></div>
</body>
</html>

app/views/pages/_breadcrumbs.html.erb
<div id="breadcrumbs">
  <% @page.ancestors.each do |page| %>
    <%= link_to page.name, page %> &gt;
  <% end %>
  <%= link_to @page.name, @page, class: "active" %>
</div>

app/views/pages/_content.html.erb
<h1><%= @page.name %></h1>

<%= simple_format @page.content %>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.collection_select :parent_id, Page.order(:name), :id, :name, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/_full_menu.html.erb
<ul>
  <% for page in Page.roots %>
      <li <%= "class=active" if current_page.root == page %> >
        <%= link_to page.name, page %>
        <%= render "submenu_of", page: page %>
      </li>
  <% end %>
</ul>

app/views/pages/_menu.html.erb
<div id="menu">
  <ul>
    <% for page in Page.roots %>
        <li <%= "class=active" if current_page.root == page %> >
          <%= link_to page.name, page %>
        </li>
    <% end %>
  </ul>
</div>

app/views/pages/_notice.html.erb
<% flash.each do |key, message| %>
  <div class="notice">
    <%= message %>
  </div>
<% end %>

app/views/pages/_root_menu.html.erb
<div id="menu">
  <ul>
    <% for page in Page.roots %>
        <li>
          <%= link_to page.name, page %>
        </li>
    <% end %>
  </ul>
</div>

app/views/pages/_submenu.html.erb
<div id="submenu">
  <%= render "submenu_of", page: @page.root %>
</div>

app/views/pages/_submenu_of.html.erb
<% if page.has_children? %>
    <ul>
      <% for child_page in page.children %>
          <li>
            <%= link_to child_page.name, child_page %>
            <%= render "submenu_of", page: child_page %> <!-- look ma, recursion! -->
          </li>
      <% end %>
    </ul>
<% end %>

app/views/pages/_submenu_pages.html.erb
<ul>
  <% pages.each do |page, children| %>
      <li>
        <%= link_to_unless_current page.name, page %>
        <%= render 'submenu_pages', pages: children if children.present? %>
      </li>
  <% end %>
</ul>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page, title: "View the page as an end-user" %> |
<%= link_to 'Back', pages_path, title: "List all the pages" %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Ancestry</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.name %></td>
    <td><%= page.content %></td>
    <td><%= page.ancestry %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<% content_for :title, @page.name %>


<%= render 'root_menu' %>

<%= render 'submenu' %>

<%= render 'breadcrumbs' %>

<%= render 'notice' %>

<%= render 'content' %>